apiVersion: v1
kind: Namespace
metadata:
  name: production

---
apiVersion: v1
kind: Service
metadata:
  name: kelompok1
  namespace: production
  labels:
    app: kelompok1
spec:
  selector:
    app: kelompok1
  ports:
    - port: 80
      name: http
      targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kelompok1
  namespace: production
spec:
  selector:
    matchLabels:
      app: kelompok1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kelompok1
    spec:
      containers:
        - name: kelompok1
          image: asia-southeast1-docker.pkg.dev/$PROJECT_ID/production/kelompok1:$SHORT_SHA
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: kelompok1
          resources:
            requests:
              cpu: 50m

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kelompok1
  namespace: production
spec:
  maxReplicas: 25
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kelompok1
  targetCPUUtilizationPercentage: 100

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kelompok1
  namespace: production
  annotations:
    kubernetes.io/ingress.global-static-ip-name: kelompok1
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: kelompok1
spec:
  rules:
    - host: app.kelompok1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kelompok1
                port:
                  number: 80

---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: kelompok1
  namespace: production
spec:
  domains:
    - app.kelompok1.com
